enum OrderStatus {
  OPEN
  IN_PROGRESS
  COMPLETE
}

type Order {
  id: ID!
  currentState: OrderStatus!
  customer: String!
  employee: Employee!
  lineItems: [String!]!
  createdAt: String!
  updatedAt: String!
}

type LineItems {
  id: ID!
  title: String!
  price: Int!
}

type Customer {
  id: ID!
  name: String!
  email: String!
  password: String!
}

type Employee {
  id: ID!
  name: String!
  email: String!
  password: String!
}

input EmployeeInput {
  name: String!
  email: String!
  password: String!
}

type Query {
  getOrder(id: ID!): Order
  getOrders: [Order!]!
  getCustomer(id: ID!): Customer
  getCustomers: [Customer!]
  getEmployee(id: ID!): Employee
  getEmployees: [Employee!]
}

type Mutation {
  # ORDER
  createOrder(customer: String!, lineItems: [String!]!): Order
  updateOrder(id: ID!, currentState: OrderStatus!, employee: EmployeeInput!): Order

  # CUSTOMER  
  createCustomer(name: String!, email: String!, password: String!): Customer
  updateCustomer(
    id: ID!
    name: String!
    email: String!
    password: String!
  ): Customer

  # EMPLOYEE
  createEmployee(name: String!, email: String!, password: String!): Employee
  updateEmployee(
    id: ID!
    name: String!
    email: String!
    password: String!
    ): Employee
}
